package com.tastingspace.tastingprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FailureReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String tastedSauceId;
	private java.lang.String tastedSauceFailureDescription;

	public FailureReport() {
	}

	public java.lang.String getTastedSauceId() {
		return this.tastedSauceId;
	}

	public void setTastedSauceId(java.lang.String tastedSauceId) {
		this.tastedSauceId = tastedSauceId;
	}

	public java.lang.String getTastedSauceFailureDescription() {
		return this.tastedSauceFailureDescription;
	}

	public void setTastedSauceFailureDescription(
			java.lang.String tastedSauceFailureDescription) {
		this.tastedSauceFailureDescription = tastedSauceFailureDescription;
	}

	public FailureReport(java.lang.String tastedSauceId,
			java.lang.String tastedSauceFailureDescription) {
		this.tastedSauceId = tastedSauceId;
		this.tastedSauceFailureDescription = tastedSauceFailureDescription;
	}

}