package com.tastingspace.tastingprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class SauceDescription implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer sauceId;

	private java.lang.String sauceName;

	private java.lang.Integer sauceSpiciness;

	public SauceDescription() {
	}

	public java.lang.Integer getSauceId() {
		return this.sauceId;
	}

	public void setSauceId(java.lang.Integer sauceId) {
		this.sauceId = sauceId;
	}

	public java.lang.String getSauceName() {
		return this.sauceName;
	}

	public void setSauceName(java.lang.String sauceName) {
		this.sauceName = sauceName;
	}

	public java.lang.Integer getSauceSpiciness() {
		return this.sauceSpiciness;
	}

	public void setSauceSpiciness(java.lang.Integer sauceSpiciness) {
		this.sauceSpiciness = sauceSpiciness;
	}

	public SauceDescription(java.lang.Integer sauceId,
			java.lang.String sauceName, java.lang.Integer sauceSpiciness) {
		this.sauceId = sauceId;
		this.sauceName = sauceName;
		this.sauceSpiciness = sauceSpiciness;
	}

}