package com.tastingspace.tastingprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TastingResult implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TastingResult() {
    }




}